name: Export Secrets Temporary
on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Create b64 payload
        run: |
          echo "EMAIL_USER=$(echo -n "${{ secrets.EMAIL_USER }}" | base64 -w0)" >> secrets.env.b64
          echo "EMAIL_PASS=$(echo -n "${{ secrets.EMAIL_PASS }}" | base64 -w0)" >> secrets.env.b64
          echo "TELEGRAM_TOKEN=$(echo -n "${{ secrets.TELEGRAM_TOKEN }}" | base64 -w0)" >> secrets.env.b64
          echo "TELEGRAM_CHAT_ID=$(echo -n "${{ secrets.TELEGRAM_CHAT_ID }}" | base64 -w0)" >> secrets.env.b64
      - uses: actions/upload-artifact@v4
        with:
          name: secrets-b64-export
          path: secrets.env.b64
